apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "dpro7026"
  - name: GitHubUser
    value: "dpro7026"
  - name: GitHubRepo
    value: "tekton_triggers_tutorial"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: "821500f6c03ce5bf07f11bf3ca8bb9bafdc72465"
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: "159.122.174.104"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
